### ISSUE TITLE
시각편집기 사용시 호스트명을 확인할 수 없는 오류 해결

### ISSUE THREAD

**Issue by HanbitGaram** [femiwiki/docker-parsoid#10]
현재 시각편집기를 사용하면

"서버에서 데이터를 불러오는 중 오류가 났습니다: apierror-visualeditor-docserver-http-error: (curl error: 6) Couldn't resolve host name 다시 시도하겠습니까?"

라는 에러가 발생합니다.

**Comment by lens0021** [comment]
파소이드와 레스트베이스가 떠있지 않고 swam manager도 아니라고 뜹니다
```
$ docker service ls
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
$ docker container ls --all
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                       NAMES
d22266eb5969        joshix/caddy:v0.11.3         "/bin/caddy"             5 weeks ago         Up 5 weeks          80/tcp, 443/tcp, 2015/tcp   mediawiki_http.1.uthod7vd9i7eu9abv1qpyt09p
14b8f3af9424        femiwiki/mediawiki:build-9   "/tini -- /usr/local…"   5 weeks ago         Up 5 weeks          9000/tcp                    mediawiki_fastcgi.1.jjn4enz5vgevotbnydz0znhhf
$ docker stack ls
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
```

**Comment by lens0021** [comment]
CloudWatch에서 보면 2019-06-10 16:00+0900 ~ 2019-06-12 21:00+0900 사이에 CPU 사용량이 급증하였다가 감소하였습니다. (5분 간격 평균)

![image](https://user-images.githubusercontent.com/28209361/59396647-bae22500-8dc4-11e9-9a85-ec208a470325.png)

이에 따라 CPU Credit Balance도 감소하여 2019-06-11 05:10+0900에 0이 되었습니다.

![image](https://user-images.githubusercontent.com/28209361/59398444-38a92f00-8dcb-11e9-9741-113a49154ce6.png)

atop은 `atop_20190613` 파일은 "can not read raw file header"라며 열리지 않았고, 이전 날짜를 확인했을 때  `CPU`*가 평소 1\~2%였던 것이 2019-06-10 06:50Z 이후로 6\~7% 정도로 증가하였습니다.

(* CPU utilization. The total occupation of all CPU's together.)

**Comment by simnalamburt** [comment]
파소이드만의 문제가 아니라 서버이슈인것이 확인되어서 이 이슈는 닫고 https://github.com/femiwiki/femiwiki/issues/84 로 옮깁니다
